spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/helptodo2
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
  datasource:
    url: jdbc:mysql://000.000.000.000:0000/todo?serverTimezone=UTC&characterEncoding=UTF-8
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace



jwt:
  secretKey: htdsp
  expiredMs: 6000000 #1000(1초) * 60 *100= 100분
